apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: customer-service
  name: customer-service
  namespace: demo
spec:
  failedBuildsHistoryLimit:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'customer-service:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: Binary
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'openjdk:8-jdk-alpine'
    type: Docker

