kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: customer-service-app
spec:
  source:
    git:
      ref: master
      uri: 'https://github.com/phoenixm103/customer-service-app'
    sourceSecret:
      name: github-secret
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: jenkins/Jenkinsfileforcustomerservice
    type: JenkinsPipeline 

